### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by jdpark7** [CodeWithEmad/chatgpt-xblock#1]
https://discuss.openedx.org/t/modulenotfounderror-no-module-named-xblock-utils/13519/4

**Comment by CodeWithEmad** [comment]
I didn't have time to update this XBlock to support the latest versions of OpenedX, so it's becoming outdated. I suspect that the pinned version of XBlock in the setup.py file is causing the issue, and we should make XBlock a loose dependency instead.

**Comment by CodeWithEmad** [comment]
I fixed the installation issue, but note that this xblock is using an older version of Openai, and installing it with other xblocks using newer versions, will cause unwanted errors.
@jdpark7
